apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickpulse.fullname" . }}
  labels:
    {{- include "clickpulse.labels" . | nindent 4 }}
type: Opaque
stringData:
  dsn: {{ .Values.clickhouse.dsn | quote }}
